### ISSUE TITLE
Problema C2D080379669 - urgentisimo

### ISSUE THREAD

**Issue by camigoma** [juan267/click2dress#25]
Estábamos metiendo esta orden al final se salió, el sistema nos saco. no lo encontramos por ningún lado si no hasta que  entramos al calendario del vestido y hay esta bloqueado pero no da opción de factura. pregunta , si quedo como un vestido????
https://click2dress.herokuapp.com/admin/orders/C2D-080379669/edit. Osea no quedo, pero si esta bloqueando el vestido.
ayudame a que quede como pedido con el numero de factura 9528

**Comment by juan267** [comment]
El problema fue causa de que al agregar al carrito le dieron dos click muy rapidos por lo cual se crearon dos envios cuando solo debia haber 1.  La solucion es borrar los items del carrito y volverlos a agregar para poder aceptar el pago
