### ISSUE TITLE
Modificación de fecha de envío

### ISSUE THREAD

**Issue by CarlosAguilar86** [juan267/click2dress#45]
Situación:
Un cliente que ha adquirido un vestido, desea solicitar un cambio en la fecha de entrega de su vestido.

Error:
El vendedor necesita modificar la fecha de entrega del vestido, pero el sistema no permite escoger la fecha deseada, si no que automáticamente asigna un día antes o un día después de la fecha sugerida.

**Comment by CarlosAguilar86** [comment]
Observación:
Si la fecha de envío se modifica, lo que hace  el sistema al momento de ingresar fecha, es ocupar los 4 días siguientes como mínimo pero con las siguientes condiciones: si es para un día Lunes que no sea festivo, el vestido se ocupará desde ese Lunes hasta el día Jueves, si se asigna para el día siguiente, es decir para el día martes, el vestido estará ocupado toda la semana hasta el día hábil de la semana siguiente y así de manera consecutiva con los siguientes días de la semana.

**Comment by juan267** [comment]
La fecha de envio se puede modificar en la pestaña de envios de cada pedido si el estado del envio del pedido es `programado`. Las condiciones para escoger las fechas son las que se estableciaron como el estandar por la compañia, no deberia ser posible salirse de estas reglas.
