### ISSUE TITLE
Modificación Arreglos

### ISSUE THREAD

**Issue by CarlosAguilar86** [juan267/click2dress#46]
Situación:
El vendedor desea modificar los arreglos que se deben hacer a un vestido alquilado.

Problema:
Cuando se va a modificar el arreglo de un vestido, la fecha de entrega queda en blanco y se borra la fecha de entrega del vestido.

**Comment by juan267** [comment]
Esto es intencional, Como el cambio en el vestido no puede ser guardado sin poner una fecha el usuario se ve obligado a hacer click en el campo de fecha momento en el cual la fecha seleccionada actual va a cargar. De esta forma se obliga a los usuarios a verificar que las fechas de alquilers de los vestidos sean correctas cada vez que los editan en una orden.
